### ISSUE TITLE
Provide TypeScript type definition

### ISSUE THREAD

**Issue by dcharbonnier** [getyoti/yoti-node-sdk#265]
No TypeScript type definition is available for this package.

**Comment by jlmartyres** [comment]
Hi,
Thank you for contacting Yoti and for your feedback.
This isn't something we're looking at right now so I will add it to our feature requests.
If you have any further comments or would like to get in touch to discuss Yoti products please feel free to contact clientsupport@yoti.com.
Kind regards,
Jason
