### ISSUE TITLE
[bug] Fails to build on Node 10+ 

### ISSUE THREAD

**Issue by kybarg** [getyoti/yoti-node-sdk#32]
`ursa` package is not supported anymore and causes yoti to fail

**Comment by echarrod** [comment]
Hi, we have opted to use an alternative package to Ursa to avoid this problem. This was released in [version 3.3.0](https://github.com/getyoti/yoti-node-sdk/releases/tag/v3.3.0), and we've tested with the following versions:

- 6.13.0
- 8.9.4
- 9.11.2
- 10.15.1
- 11.10.0
