### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by drakedeatonuk** [getyoti/yoti-node-sdk#418]
I appreciate other's have posted similar issues, but it begs repeating - typescript support would be immensely valuable.

Without type definitions it takes a new developer vastly longer to learn a new api.

**Comment by jhackett1** [comment]
the people want types!

**Comment by drakedeatonuk** [comment]
I lost a week of dev time do figuring out the types. Even then, the types I've made are quite flawed and as a result the implementation of this api that I've been able to write is less extensible. Do I have time to improve it? Unfortunately not. Will this mean in the future making changes to our yoti api integration will take longer? Absolutely. Are we less likely to implement a Digital ID integration now? YES. Was this all avoidable if Yoti would just release a type library? 100%.

Yoti dev team - please push for this to your PMs!
