### ISSUE TITLE
Yoti button websocket error

### ISSUE THREAD

**Issue by jamiehill** [getyoti/yoti-node-sdk#88]
Am posting here as I have no idea where else to post this.  There's no help/support section on the website, and I can't find any mention of the `www.yoti.com/share/client` share button code in existence!

I'm adding the share button code to my spa html, and it is correctly displaying the Yoti button.  When I click it, it momentarily shows the qr code iframe, before trying to instantiate the websocket connection, which fails, resulting in `Sorry, there was a technical issue'

Here's the devtools request:

```
Request URL: wss://api.yoti.com/api/v1/connect-sessions/proto_CiQxNGMxNmFjMC1kZmU5LTQzY2UtYjMwNS02ODdhY2JjYmIwYWISCTAudGh3LmdichoIRDl4Yzhna3Q=
Request Method: GET
Status Code: 400 Bad Request
```

Please help, as my initial experience of integrating yoti, has proved frustratiing.

**Comment by jlmartyres** [comment]
Hi Jamie,

Details of the integration can be found here: https://developers.yoti.com/yoti-app

Support is also available via the following email address: sdksupport@yoti.com

Please feel free to email in if you still need some help with the integration
